version: "3.8"
services:
  app:
    build: .
    image: australia-southeast2-docker.pkg.dev/sit737-24t1-rajakaruna-9be57e0/cloud-native-unit/node-web-app:latest
    ports:
      - "3040:3040"
    environment:
      - PORT=3040
    container_name: my-app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3040/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
