apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: myapp
    tier: microservice
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: mynode
          imagePullPolicy: Never
          image: keshjay/node-web-app:latest
          ports:
            - containerPort: 3040
