apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 32001
      targetPort: 27017
  type: LoadBalancer
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongo-service
# spec:
#   selector:
#     app: mongo
#   ports:
#     - protocol: TCP
#       port: 27017   # Internal port used by MongoDB
#       targetPort: 27017
#   type: LoadBalancer
